tasks:
  - name: todonativemobileapp
    before: |
      cd /workspace/workshop-todo-native-mobile
      nvm install node
      npm install
      npm install -g expo-cli
      npm install -g netlify-cli
      npm install astra-setup
      npm install whatwg-fetch
      npm install -g @expo/ngrok
      npm install @expo/ngrok@4.1.0
      npm install react-native-gesture-handler
      npm install @react-native-segmented-control/segmented-control
      npm install @expo-google-fonts/inter --legacy-peer-deps
      npm install babel-plugin-inline-dotenv --legacy-peer-deps

    command: |
      gp open README.md
      echo "todonativemobileapp gitpod ready - LET'S DO THIS!"
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 8888
    onOpen: open-browser
    visibility: public
  - port: 19000
    onOpen: ignore
    visibility: public
  - port: 19001
    onOpen: ignore
    visibility: public
  - port: 19002
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: ignore  
  - port: 4040
    onOpen: ignore
    visibility: public
  - port: 5037
    onOpen: ignore
    visibility: public

